# Generated by Django 5.1.4 on 2024-12-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dish_table_alter_menu_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='menu_order',
        ),
        migrations.AlterModelTable(
            name='orderlist',
            table='menu_orderlist',
        ),
    ]
