# Generated by Django 5.1.4 on 2024-12-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_authmodel_options_remove_authmodel_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='authmodel',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrator')], default='client', max_length=10),
        ),
        migrations.AlterField(
            model_name='authmodel',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authmodel',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
